from graphviz import Digraph

f = Digraph('finite_state_machine', filename='fsm.gv')
f.attr(rankdir='LR', size='8,5')

f.attr('node', shape='doublecircle')
f.node('-1')
f.node('-2')
f.node('-3')
f.node('-4')
f.node('-5')
f.node('-6')

f.attr('node', shape='circle')
f.edge('0', '1', label='y')
f.edge('0', '3', label='n')
f.edge('0', '4', label='x')
f.edge('0', '6', label='z')
f.edge('0', '-5', label='e,s,o,r,1,other')
f.edge('1', '2', label='e')
f.edge('1', '6', label='y,x,z,1')
f.edge('1', '-4', label='s,n,o,r,other')
f.edge('2', '-1', label='s')
f.edge('2', '-6', label='y,e,n,o,x,r,z,1,other')
f.edge('3', '-2', label='o')
f.edge('3', '-6', label='y,e,s,n,x,r,z,1,other')
f.edge('4', '5', label='o')
f.edge('4', '6', label='x,y,z,1')
f.edge('4', '-4', label='e,s,n,r,other')
f.edge('5', '-3', label='r')
f.edge('5', '-6', label='y,e,s,n,o,x,z,1,other')
f.edge('6', '6', label='x,y,z,1')
f.edge('6', '-4', label='e,s,n,o,r,other')

f.view()